
suite:
    format: yaml
    
    path: ./suites
    tests-path: ./tests
    objects-path: ./objects
    reports-path: ./reports
    
    isParallel: true
    thread-count: 2    
    
    driver: firefox
    timeout: 15000

    remoteUrl: #http://localhost:4444/wd/hub

    suites: 
        - duckduckgo-suite.yaml


logging:
    file: logs/suiterunner.log
    level:
        root: INFO
        org.ao: DEBUG
