/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ahmetozkesek' at '11/11/16 13:58' with Gradle 3.2-rc-2
 *
 * @author ahmetozkesek, @date 11/11/16 13:58
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
